# Triggers the pipeline for main, dev, and qa branches.
trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

# References a variable group called snowflake-credentials which should contain all your Snowflake connection details.
variables:
  - group: snowflake-credentials

# Sets up Python 3.8 and installs the necessary dependencies.
stages:
- stage: PythonSetup
  jobs:
  - job: SetupPython
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        addToPath: true
    - script: |
        /opt/hostedtoolcache/Python/3.8.18/x64/bin/python3 --version  # Check Python version
        /opt/hostedtoolcache/Python/3.8.18/x64/bin/python3 -m pip install --upgrade pip  # Upgrade pip
        /opt/hostedtoolcache/Python/3.8.18/x64/bin/python3 -m pip install snowflake-connector-python  # Install Snowflake connector
        /opt/hostedtoolcache/Python/3.8.18/x64/bin/python3 -m pip show snowflake-connector-python  # Verify installation
      displayName: 'Setup Python and Install dependencies'

# Sets up private key in secure files
- stage: DownloadPrivateKey
  dependsOn: PythonSetup
  jobs:
  - job: DownloadPrivateKeyFile
    steps:
    - task: DownloadSecureFile@1
      name: privateKeyFile
      inputs:
        secureFile: '$(private_key_file_name)'
      displayName: 'Download Snowflake private key'
    - script: |
        mkdir .secure_files
        cp $(privateKeyFile.secureFilePath) .secure_files/
      displayName: 'Copy private key to secure files directory'

# Test Snowflake Connection
- stage: TestConnection
  dependsOn: DownloadPrivateKey
  jobs:
  - job: TestSnowflakeConnection
    steps:
    - task: DownloadSecureFile@1
      name: privateKeyFile
      inputs:
        secureFile: '$(private_key_file_name)'
      displayName: 'Download Snowflake private key'
    - script: |
        mkdir -p .secure_files
        cp $(privateKeyFile.secureFilePath) .secure_files/
        ls -la .secure_files/
        /opt/hostedtoolcache/Python/3.8.18/x64/bin/python3 /home/vsts/work/1/s/test_connection.py
#        python test_connection.py
      env:
        SNOWFLAKE_ACCOUNT: $(account)
        SNOWFLAKE_USER: $(user)
        #SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: $(private_key_file_pwd)
        SNOWFLAKE_PRIVATE_KEY_FILE: '.secure_files/$(private_key_file_name)'
        SNOWFLAKE_WAREHOUSE: $(warehouse)
        SNOWFLAKE_ROLE: $(role)
        SNOWFLAKE_DATABASE: $(database)
        SNOWFLAKE_SCHEMA: $(schema)
      displayName: 'Test Snowflake connection'
  